"""Fidelity-tier call counting for agent runs.

Phase-2 of the project asks whether an agent allocates simulation fidelity
sensibly. That is only measurable if every model call is counted while the agent
runs — it cannot be reconstructed afterwards. So the harness prepends a
directory holding a generated `sitecustomize.py` to PYTHONPATH. CPython imports
`sitecustomize` at interpreter startup, so any `python` the agent shells out to
is instrumented without the agent having to cooperate.

Each patched call appends one JSON object to the file named by AEDL_CALL_LOG.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any

#: fidelity tier -> "module:attribute" entry points to time and count.
TIERS: dict[str, list[str]] = {
    "aperture_model": [
        "phased_array:compute_full_pattern",
        "phased_array:compute_pattern_cuts",
        "phased_array:compute_pattern_uv_space",
        "phased_array:compute_pattern_vs_frequency",
        "phased_array:array_factor_vectorized",
        "phased_array:array_factor_fft",
    ],
    "reduced_order": [
        "phased_array_systems:evaluate_case",
        "phased_array_systems:evaluate_config",
        # opensatcom's entry point is a method; the dotted form patches the
        # class object, which every import spelling shares.
        "opensatcom.link.engine:DefaultLinkEngine.evaluate_snapshot",
    ],
    # Tier-1 full-wave. Absent until EdgeFEM is wired in; the payload skips
    # entry points whose module will not import.
    "full_wave": [
        "edgefem:solve",
    ],
}

_PAYLOAD = '''\
# Generated by aedl.harness.instrument. Counts model calls by fidelity tier.
import json, os, sys, time

_LOG = os.environ.get("AEDL_CALL_LOG")
_TIERS = json.loads(os.environ.get("AEDL_CALL_TIERS", "{}"))


def _record(tier, func, wall_s, nested):
    if not _LOG:
        return
    try:
        with open(_LOG, "a") as fh:
            fh.write(json.dumps({
                "ts": time.time(), "tier": tier, "func": func,
                "wall_s": round(wall_s, 6), "nested": nested, "pid": os.getpid(),
            }) + "\\n")
    except OSError:
        pass


# Higher-level entry points call lower-level ones internally (compute_full_pattern
# -> array_factor_vectorized). Depth tracking marks those so the headline count
# reflects evaluations the caller actually asked for.
_depth = [0]


def _make_wrapper(original, tier, label):
    def wrapper(*args, **kwargs):
        nested = _depth[0] > 0
        _depth[0] += 1
        start = time.perf_counter()
        try:
            return original(*args, **kwargs)
        finally:
            _depth[0] -= 1
            _record(tier, label, time.perf_counter() - start, nested)

    wrapper._aedl_wrapped = True
    try:
        wrapper.__name__ = getattr(original, "__name__", "wrapped")
        wrapper.__doc__ = getattr(original, "__doc__", None)
    except (AttributeError, TypeError):
        pass
    return wrapper


def _patch(module, attr, tier):
    """Wrap module.attr, and the same name in the module that defines it.

    Re-exported functions (phased_array.compute_full_pattern lives in
    phased_array.core) must be patched in both namespaces, otherwise a
    `from phased_array.core import ...` slips past uncounted.

    A dotted attr ("ClassName.method") patches the method on the class
    object. The class object is shared by every import spelling, so the
    dual-namespace dance is unnecessary there, and the wrapper binds self
    like any plain function assigned to a class.
    """
    if "." in attr:
        owner_name, _, meth = attr.partition(".")
        owner = getattr(module, owner_name, None)
        if owner is None:
            return
        original = owner.__dict__.get(meth)
        if original is None or getattr(original, "_aedl_wrapped", False):
            return
        label = module.__name__ + ":" + attr
        setattr(owner, meth, _make_wrapper(original, tier, label))
        return

    original = getattr(module, attr, None)
    if original is None or getattr(original, "_aedl_wrapped", False):
        return
    label = module.__name__ + ":" + attr
    wrapper = _make_wrapper(original, tier, label)
    setattr(module, attr, wrapper)

    home = sys.modules.get(getattr(original, "__module__", "") or "")
    if home is not None and home is not module:
        if getattr(home, attr, None) is original:
            setattr(home, attr, wrapper)


_TARGETS = {}
for _tier, _entries in _TIERS.items():
    for _entry in _entries:
        _mod, _, _attr = _entry.partition(":")
        _TARGETS.setdefault(_mod, []).append((_attr, _tier))


def _patch_module(name):
    module = sys.modules.get(name)
    if module is None:
        return
    for attr, tier in _TARGETS.get(name, ()):
        _patch(module, attr, tier)


class _PatchingLoader:
    """Delegating loader that patches the module after it executes."""

    def __init__(self, inner, name):
        self._inner = inner
        self._name = name

    def create_module(self, spec):
        return self._inner.create_module(spec)

    def exec_module(self, module):
        self._inner.exec_module(module)
        _patch_module(self._name)

    def __getattr__(self, item):
        return getattr(self._inner, item)


class _Finder:
    def find_spec(self, fullname, path=None, target=None):
        if fullname not in _TARGETS:
            return None
        for finder in sys.meta_path:
            if finder is self:
                continue
            try:
                spec = finder.find_spec(fullname, path, target)
            except (AttributeError, ImportError):
                continue
            if spec is not None and spec.loader is not None:
                spec.loader = _PatchingLoader(spec.loader, fullname)
                return spec
        return None


sys.meta_path.insert(0, _Finder())

# Anything already imported before this ran (unlikely, but cheap to cover).
for _name in _TARGETS:
    _patch_module(_name)

# Chain to any sitecustomize that was already on the path behind us.
_self = os.path.dirname(os.path.abspath(__file__))
_rest = [p for p in sys.path if os.path.abspath(p or ".") != _self]
for _entry in _rest:
    _candidate = os.path.join(_entry, "sitecustomize.py")
    if os.path.exists(_candidate):
        import importlib.util as _u
        _spec = _u.spec_from_file_location("_aedl_prev_sitecustomize", _candidate)
        if _spec and _spec.loader:
            _mod = _u.module_from_spec(_spec)
            try:
                _spec.loader.exec_module(_mod)
            except Exception:
                pass
        break
'''


def write_payload(directory: Path) -> Path:
    """Write the sitecustomize shim and return the directory to put on PYTHONPATH."""
    directory.mkdir(parents=True, exist_ok=True)
    (directory / "sitecustomize.py").write_text(_PAYLOAD)
    return directory


def build_env(
    base_env: dict[str, str],
    shim_dir: Path,
    call_log: Path,
    tiers: dict[str, list[str]] | None = None,
) -> dict[str, str]:
    env = dict(base_env)
    existing = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = f"{shim_dir}{':' + existing if existing else ''}"
    env["AEDL_CALL_LOG"] = str(call_log)
    env["AEDL_CALL_TIERS"] = json.dumps(TIERS if tiers is None else tiers)
    return env


def summarize(call_log: Path) -> dict[str, Any]:
    """Aggregate a call log into per-tier counts and cumulative wall time."""
    counts: dict[str, int] = defaultdict(int)
    seconds: dict[str, float] = defaultdict(float)
    by_func: dict[str, int] = defaultdict(int)
    total = 0
    nested_total = 0
    if call_log.exists():
        for line in call_log.read_text().splitlines():
            if not line.strip():
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            if rec.get("nested"):
                nested_total += 1
                continue
            counts[rec["tier"]] += 1
            seconds[rec["tier"]] += float(rec.get("wall_s", 0.0))
            by_func[rec.get("func", "?")] += 1
            total += 1
    return {
        "total_calls": total,
        "nested_calls": nested_total,
        "calls_by_tier": dict(counts),
        "seconds_by_tier": {k: round(v, 4) for k, v in seconds.items()},
        "calls_by_function": dict(by_func),
    }
